package com.mtcdb.stem.mathtrix.calculator.options

import android.annotation.*
import android.os.*
import android.view.*
import android.widget.*
import androidx.fragment.app.*
import com.google.android.material.button.*
import com.google.android.material.dialog.*
import com.google.android.material.textfield.*
import com.google.android.material.textview.*
import com.mtcdb.stem.mathtrix.*

class PaybackPeriodFragment : Fragment() {

    private lateinit var initialInvestmentEditText : TextInputEditText
    private lateinit var annualCashFlowEditText : TextInputEditText
    private lateinit var calculateButton : MaterialButton
    private lateinit var resultTextView : MaterialTextView
    private lateinit var description : TextView
    private lateinit var buttonSolution : Button

    @SuppressLint("MissingInflatedId")
    override fun onCreateView(
        inflater : LayoutInflater, container : ViewGroup?,
        savedInstanceState : Bundle?,
    ) : View? {
        val view = inflater.inflate(
            com.calculator.calculatoroptions.R.layout.fragment_payback_period,
            container,
            false
        )

        // Initialize UI components
        initialInvestmentEditText =
            view.findViewById(com.calculator.calculatoroptions.R.id.editTextInitialInvestment)
        annualCashFlowEditText =
            view.findViewById(com.calculator.calculatoroptions.R.id.editTextAnnualCashFlow)
        calculateButton =
            view.findViewById(com.calculator.calculatoroptions.R.id.buttonCalculatePaybackPeriod)
        resultTextView =
            view.findViewById(com.calculator.calculatoroptions.R.id.textViewPaybackPeriodResult)
        description = view.findViewById(com.calculator.calculatoroptions.R.id.description)
        buttonSolution = view.findViewById(com.calculator.calculatoroptions.R.id.buttonSolution)

        calculateButton.setOnClickListener {
            calculatePaybackPeriod()
        }

        val paybackPeriodDescription = """
            The Payback Period is a simple financial metric that represents the time it takes for an investment to generate cash equal to its initial cost. It is often used to assess the risk associated with an investment by determining how quickly the initial investment can be recovered.

            The formula for calculating the Payback Period is:

            Payback Period = Initial Investment / Annual Cash Flow

            Let's consider an example to illustrate the calculation:

            Suppose you have an initial investment of ₱50,000 and the annual cash flow generated by the investment is ₱10,000.

            Payback Period = ₱50,000 / ₱10,000
                           = 5 years

            In this example, the Payback Period is 5 years, indicating that it would take 5 years for the investment to generate enough cash to recover the initial investment.

            Keep in mind that the Payback Period is a simplistic metric and may not consider the time value of money. It is commonly used for quick assessments of the recovery period.
        """.trimIndent()


        description.text = paybackPeriodDescription

        buttonSolution.setOnClickListener {
            val initialInvestment =
                initialInvestmentEditText.text.toString().toDoubleOrNull() ?: 0.0
            val annualCashFlow =
                annualCashFlowEditText.text.toString().toDoubleOrNull() ?: 0.0

            val paybackPeriod = initialInvestment / annualCashFlow

            resultTextView.text =
                getString(
                    com.calculator.calculatoroptions.R.string.payback_period_result,
                    paybackPeriod
                )
            showExplanationDialog(
                initialInvestment,
                annualCashFlow,
                paybackPeriod
            )
        }

        return view
    }

    override fun onDestroy() {
        val mainActivity = requireActivity() as MainActivity
        mainActivity.toolbar.title = getString(R.string.calculator)
        super.onDestroy()
    }

    private fun calculatePaybackPeriod() {
        val initialInvestment =
            initialInvestmentEditText.text.toString().toDoubleOrNull() ?: 0.0
        val annualCashFlow =
            annualCashFlowEditText.text.toString().toDoubleOrNull() ?: 0.0

        val paybackPeriod = initialInvestment / annualCashFlow

        resultTextView.text =
            getString(
                com.calculator.calculatoroptions.R.string.payback_period_result,
                paybackPeriod
            )
    }

    private fun showExplanationDialog(
        initialInvestment : Double,
        annualCashFlow : Double,
        paybackPeriod : Double,
    ) {
        val explanation = """
            The Payback Period is a financial metric that measures the time it takes for an investment to generate cash equal to its initial cost.

            The formula for calculating the Payback Period is:

            Payback Period = Initial Investment / Annual Cash Flow

            Given:
                Initial Investment = $initialInvestment
                Annual Cash Flow = $annualCashFlow

            Solution:
                Payback Period = $initialInvestment / $annualCashFlow
                Payback Period = $paybackPeriod years

            Therefore, the Payback Period is $paybackPeriod years.
        """.trimIndent()

        // Display explanation in a custom dialog
        MaterialAlertDialogBuilder(requireContext())
            .setTitle("Payback Period Calculation")
            .setMessage(explanation)
            .setPositiveButton("OK", null)
            .show()
    }
}
